### ISSUE TITLE
Add the correct links in the readme file

### ISSUE THREAD

**Issue by sishubjoshi** [sishubjoshi/DSA#2]

**Comment by akshaydmc** [comment]
I can do it for you

**Comment by sishubjoshi** [comment]
okay..
The correct links to be added are the ones marked below:

### Linked list
Singly Linked List :heavy_check_mark:
Doubly Linked List :heavy_check_mark:

### Implementation
String sum(java) :heavy_check_mark:

**Comment by akshaydmc** [comment]
I've changed them check the pull request.
